version: "3"

services:

  app2:
    image: app2
    container_name: app2
    restart: always
    network_mode: "host"
    #ports:
    #  - "9001:9001"

  app1:
    image: app1
    container_name: app1
    restart: always
    network_mode: "host"
    #ports:
    #  - "9000:9000"
    depends_on:
      - app2

