version: "3"

services:

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    hostname: jaeger
    restart: always
    networks:
      - tracenet
    ports:
      - "16686:16686"
      - "14268:14268" #used by Kamon
      - "14250"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    hostname: otel-collector
    restart: always
    networks:
      - tracenet
    command: ["--config=/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/otel-collector-config.yml

    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "55679:55679" # zpages extension
      - "4317:4317"
    depends_on:
      - jaeger

  app3:
    image: app3
    container_name: app3
    hostname: app3
    restart: always
    environment:
      - OTEL_SERVICE_NAME=app3
      - OTEL_TRACES_EXPORTER=jaeger
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14250
      - OTEL_EXPORTER_JAEGER_TIMEOUT=10000
    networks:
      - tracenet
    ports:
      - "9002:9002"

  app2:
    image: app2
    container_name: app2
    hostname: app2
    restart: always
    networks:
      - tracenet
    ports:
      - "9001:9001"

  app1:
    image: app1
    container_name: app1
    hostname: app1
    restart: always
    networks:
      - tracenet
    ports:
      - "9000:9000"
    depends_on:
      - app2
      - jaeger

networks:
  tracenet:
