# .github/workflows/dependency-graph.yml
name: Update Dependency Graph
on:
  workflow_dispatch:

jobs:
  dependency-graph:
    name: Update Dependency Graph
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: scalacenter/sbt-dependency-submission@v2