name: Dependency check
on:
  workflow_dispatch:

env:
  JAVA_VERSION: '1.11.0.19'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: coursier/setup-action@v1
        with:
          jvm: temurin:${{env.JAVA_VERSION}}
          apps: sbt
      - name: DependencyCheck
        run: sbt -v -Dfile.encoding=UTF-8 dependencyCheck
      - name: Print DependencyCheck Result
        uses: albuch/sbt-dependency-check-action@v1.0
        with:
          jsonReportPath: "app1/target/scala-3.4.0/dependency-check-report.json"
